name: 🐛 Bug Report
description: Something isn't working as expected? Please provide as much detail as possible.
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill in the fields below as accurately as possible.
  - type: input
    id: integration_version
    attributes:
      label: Integration Version
      description: Which version of the CloudStash integration is installed?
      placeholder: e.g. v1.0.0 or "current main branch"
    validations:
      required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: Which Home Assistant version are you using?
      placeholder: e.g. 2025.2.0
    validations:
      required: true
  - type: dropdown
    id: ha_installation_type
    attributes:
      label: Home Assistant Installation Type
      description: How did you install Home Assistant?
      options:
        - Home Assistant OS
        - Home Assistant Supervised
        - Home Assistant Container
        - Home Assistant Core (Python venv)
        - Other / Not sure
    validations:
      required: true
  - type: input
    id: storage_provider
    attributes:
      label: S3-Compatible Storage Provider
      description: Which storage provider are you using?
      placeholder: e.g. AWS S3, MinIO, Wasabi, Backblaze B2, Cloudflare R2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is the problem?
      description: Describe the bug in as much detail as possible. What did you expect and what happened instead?
      placeholder: Error message, unexpected behaviour, etc.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can the problem be reliably reproduced?
      placeholder: |
        1. Go to Settings → System → Backups
        2. Click "Create Backup"
        3. Error occurs
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Home Assistant Log Output
      description: Relevant entries from the Home Assistant log (if available). Filter for `cloudstash`.
      render: shell
  - type: textarea
    id: config
    attributes:
      label: Relevant Configuration
      description: If applicable – share relevant configuration details (endpoint URL format, bucket name, etc.). Do NOT share access keys!
      render: yaml
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (screenshots, network setup, etc.).
